### ISSUE TITLE
Version tag missing from docker plugin in pom.xml

### ISSUE THREAD

**Issue by vikramkhatri** [IBMStockTrader/notification-twitter#2]
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.stocktrader:notification-twitter:war:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for io.fabric8:docker-maven-plugin is missing. @ line 126, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building StockTrader - notification-twitter 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------

**Comment by jwalcorn** [comment]
Fixed today.
